manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: 4mplelab
      url-base: https://github.com/4mplelab
  projects:
    - name: zmk
      remote: zmkfirmware
      # main branch @ 2026-08-06 (Zephyr v4.1.0+zmk-fixes)
      revision: 268b1b1e82150460f00fd701bcd08583d5c75d29
      import: app/west.yml
    - name: zmk-driver-paw3222
      remote: sekigon-gonnoc
      # Resolved before the 2026-09-19 trackball changes.
      revision: df652881be2520bde4f64ab6ca35e4c5708f4f9b
    - name: zmk-rgbled-widget
      remote: caksoylar
      # Resolved before the 2026-09-19 trackball changes.
      revision: e6b467792a1dabef8cfa5c9fd26bfefc9c16662b
    - name: zmk-feature-charge-indicator
      remote: 4mplelab
      # Resolved before the 2026-09-19 trackball changes.
      revision: f0d311ed7804cda0e5837ef902f0419aeace4a88
  self:
    path: config
